/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PacientesObjectPageObjectPage journey");

        opaTest("Navigate to PacientesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePacientesList.onFilterBar().iExecuteSearch();

            Then.onThePacientesList.onTable().iCheckRows();
            When.onThePacientesList.onTable().iPressRow(0);

            Then.onThePacientesObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePacientesObjectPage.iCheckNumberOfSections(2);
            When.onThePacientesObjectPage.iPressSectionIconTabFilterButton("FieldGroup::DatosPersonales");
            Then.onThePacientesObjectPage.iCheckSection({ section: "FieldGroup::DatosPersonales" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::DatosPersonales" }).iCheckField({ property: "nombre" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::DatosPersonales" }).iCheckField({ property: "apellido" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::DatosPersonales" }).iCheckField({ property: "dni" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::DatosPersonales" }).iCheckField({ property: "fechaNacimiento" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::DatosPersonales" }).iCheckField({ property: "telefono" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::DatosPersonales" }).iCheckField({ property: "email" });
            When.onThePacientesObjectPage.iPressSectionIconTabFilterButton("FieldGroup::ObraSocial");
            Then.onThePacientesObjectPage.iCheckSection({ section: "FieldGroup::ObraSocial" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::ObraSocial" }).iCheckField({ property: "obraSocial" });
            Then.onThePacientesObjectPage.onForm({ section: "FieldGroup::ObraSocial" }).iCheckField({ property: "numeroAfiliado" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});